# Publish this VSCode Extension to the VSCode Marketplace and OpenVSIX Marketplace

name: Publish to Marketplaces
on:
  release:
    types: [created]
  workflow_dispatch:
jobs:
  vscemp:
    name: VScode Marketplace
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # https://github.com/actions/setup-node/issues/32#issuecomment-525791142
      - name: Get Node Version
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: yarn

      - name: Install Vsce
        run: npm i -g vsce

      - name: Publish to VScode Marketplace
        if: github.event_name != 'workflow_dispatch'
        run: vsce publish -p ${{ secrets.VSCE_TOKEN }}

  openvsix:
    name: OpenVSIX Marketplace
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # https://github.com/actions/setup-node/issues/32#issuecomment-525791142
      - name: Get Node Version
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: yarn

      - name: Install Ovsx
        run: npm i -g ovsx

      - name: Publish to OpenVSIX Marketplace
        if: github.event_name != 'workflow_dispatch'
        run: ovsx publish -p ${{ secrets.OPENVSX_TOKEN }}
