# Publish this VSCode Extension to the VSCode Marketplace and OpenVSX Marketplace

name: Publish to Marketplaces
on:
  release:
    types: [created]
  workflow_dispatch:
jobs:
  vscode:
    name: VSCode Marketplace
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '${{ vars.NODE_VERSION }}'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: yarn

      - name: Install Vsce
        run: npm i -g vsce

      - name: Publish to VSCode Marketplace
        if: github.event_name != 'workflow_dispatch'
        run: vsce publish -p ${{ secrets.VSCE_TOKEN }}

  openvsx:
    name: OpenVSX Marketplace
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '${{ vars.NODE_VERSION }}'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: yarn

      - name: Install Ovsx
        run: npm i -g ovsx

      - name: Publish to OpenVSX Marketplace
        if: github.event_name != 'workflow_dispatch'
        run: ovsx publish --yarn -p ${{ secrets.OPENVSX_TOKEN }}
