# Publish this VSCode Extension to the VSCode Marketplace and OpenVSIX Marketplace

name: Publish to Marketplaces
on:
  release:
    types: [created]
  workflow_dispatch:
jobs:
  build:
    name: VScode Marketplace
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # https://github.com/actions/setup-node/issues/32#issuecomment-525791142
      - name: Get Node Version
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: yarn

      - name: Install Vsce
        run: npm i -g vsce

      - name: Publish to VScode Marketplace
        if: github.event_name == 'workflow_dispatch'
        run: echo ${{ secrets.VSCE_PAT }}

      # - name: Install PNPM
      #   uses: pnpm/action-setup@v2
      #   with:
      #     version: 7.29.0

      # - name: Setup Node
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '16.15.1'
      #     registry-url: 'https://registry.npmjs.org'

      # - name: Install dependencies
      #   run: pnpm install --frozen-lockfile

      # - name: Pre-package Test
      #   if: github.event_name == 'workflow_dispatch'
      #   run: pnpm prepublishOnly

      # - name: Publish package to NPM
      #   if: github.event_name != 'workflow_dispatch'
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      #   run: npm publish
